event_info:
  default: event_info.yaml
network:
  default: network.yaml
logger:
  wandb:
    project: "anomaly-detection"
    entity: "ytchou97-university-of-washington"
    name: "paper-EPS-pretrain"
    run_name: &logger_name "nominal-test"
    tags: [ "Pretrain", "NERSC", "Multi-Node", "2700M", "SmallModel", "Vanilla", "test" ]
    simplified: false
  local:
    save_dir: "log"
    name: *logger_name
    version: "test-2"
options:
  Dataset:
    dataset_limit: 1.0
    normalization_file: "[place holder, will be overwritten by our script]"
  ProgressiveTraining:
    stages:
    - epoch_ratio: 1.0
      loss_weights:
        assignment:
        - 0.0
        - 0.0
        classification:
        - 0.0
        - 0.0
        classification-noised:
        - 0.0
        - 0.0
        generation:
        - 1.0
        - 1.0
        generation-recon:
        - 1.0
        - 1.0
        regression:
        - 0.0
        - 0.0
      name: full_training
      train_parameters:
        ema_decay:
        - 0.999
        - 0.999
        noise_prob:
        - 1.0
        - 1.0
        reco_attn_mask:
        - 0.0
        - 0.0
      transition_ratio: 0.0
  Training:
    Components:
      GlobalGeneration:
        include: true
      ReconGeneration:
        include: true
    epochs: 1000
    model_checkpoint_load_path: null
    model_checkpoint_save_path: "[place holder, will be overwritten by our script]"
    patience: 1000
    pretrain_model_load_path: "[your_pretrain_model.ckpt]"
  default: options.yaml
platform:
  batch_size: 4096
  data_parquet_dir: "[place holder, will be overwritten by our script]"
  number_of_workers: 2
  prefetch_batches: 2
  resources_per_worker:
    CPU: 28
    GPU: 1
resonance:
  default: resonance.yaml