input:
  event_info: "event_info.yaml"

fit:
  bkg-fit-degree: 5

workdir: "EveNet-Full"

output:
  plotdir: 'results/paper-pretrain'
  storedir: '/pscratch/sd/t/tihsu/test_AD/pretrain-result'

image: 'docker:avencast1994/evenet:1.5'

train:
  config: 'full_train.yaml'
train-cls:
  config: 'full_train_cls.yaml'
config_workflow: 'data_config.yaml'

mass-windows:
  SB-left: 5.0
  SR-left: 9.0
  SR-right: 10.6
  SB-right: 16.0
  SR-bins: 12

wandb: 'pretrain'

padding:
  pad-number: 2